# dbt_project.yml
name: data_eng_assignment
version: "1.0"
config-version: 2

profile: data_eng_assignment

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  # The `csv_uri` variable will be accessible in all resources
  csv_uri: ''

models:
  data_eng_assignment:              # <<< ต้องตรงกับ name ด้านบน
    +materialized: view             # ค่า default สำหรับทั้งโปรเจกต์ (จะถูก override ด้านล่าง)
    +schema: analytics              # ใส่ schema รวม (ปรับตามต้องการ)

    staging:
      +materialized: view           # ชั้น staging เป็น view
      # ถ้าต้องการ schema แยก:
      # +schema: staging

    dim:
      +materialized: table

    # marts:
    #   +materialized: table